# Generated by Django 4.2.23 on 2025-07-26 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_excerpt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='customer',
            field=models.CharField(max_length=100),
        ),
    ]
