# Generated by Django 4.2.23 on 2025-07-28 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_updated_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='retification',
            new_name='rectification',
        ),
    ]
