# Generated by Django 4.2.23 on 2025-07-26 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='body',
            field=models.TextField(default='Thanks!'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='approved',
            field=models.TextField(default=False),
        ),
    ]
